"""initial schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import JSON
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.create_table("users",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("display_name",sa.String(120),nullable=False),sa.Column("bio",sa.Text()),sa.Column("profile_data",JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)))
    op.create_table("subjects",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("subject_type",sa.String(50),nullable=False),sa.Column("name",sa.String(240),nullable=False),sa.Column("canonical_key",sa.String(300),nullable=False),sa.Column("canonical_identifiers",JSON(),nullable=False),sa.Column("metadata_json",JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("subject_type","canonical_key",name="uq_subject_type_key"))
    op.create_table("schema_definitions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("subject_type",sa.String(50),nullable=False),sa.Column("version",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("json_schema",JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("subject_type","version",name="uq_schema_subject_version"))
    op.create_table("experiences",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("owner_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("subject_id",sa.Uuid(),sa.ForeignKey("subjects.id"),nullable=False),sa.Column("subject_type",sa.String(50),nullable=False),sa.Column("schema_version",sa.String(20),nullable=False),sa.Column("publication_status",sa.String(20),nullable=False),sa.Column("visibility",sa.String(20),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("headline",sa.String(240),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("common_data",JSON(),nullable=False),sa.Column("domain_data",JSON(),nullable=False),sa.Column("provenance",JSON(),nullable=False),sa.Column("consent",JSON(),nullable=False),sa.Column("created_by_client",sa.String(120),nullable=False),sa.Column("auth_subject",sa.String(200),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("deleted_by",sa.String(200)))
    op.create_table("profile_signals",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("dimension",sa.String(100),nullable=False),sa.Column("value",sa.Float(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("supporting_evidence_ids",JSON(),nullable=False),sa.Column("supersedes_signal_id",sa.Uuid()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("pairwise_alignments",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("source_user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("target_user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("dimensions",JSON(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("source_user_id","target_user_id",name="uq_alignment_pair"))
    op.create_table("idempotency_records",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("client_id",sa.String(120),nullable=False),sa.Column("key",sa.String(200),nullable=False),sa.Column("request_hash",sa.String(64),nullable=False),sa.Column("response_status",sa.Integer(),nullable=False),sa.Column("response_body",JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("client_id","key",name="uq_idempotency_client_key"))
    op.create_table("audit_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("actor_id",sa.String(200),nullable=False),sa.Column("client_id",sa.String(120),nullable=False),sa.Column("action",sa.String(100),nullable=False),sa.Column("object_type",sa.String(50),nullable=False),sa.Column("object_id",sa.String(200),nullable=False),sa.Column("request_id",sa.String(100),nullable=False),sa.Column("details",JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ["audit_events","idempotency_records","pairwise_alignments","profile_signals","experiences","schema_definitions","subjects","users"]:op.drop_table(t)
